language: node_js
node_js:
  - "8.12.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test
  - npm run coveralls